import {AutopsyProtocol} from "../../models/autopsy-protocol.model";

export var MOCKED_PROTOCOLS: AutopsyProtocol[] = [
    {id: '999', caseNumber: '123', deceasedName: 'andrzej'},
    {
        id: '997',
        caseNumber: '2137',
        deceasedName: 'jan pawel',
        gender: "Other",
        findings: {internalExamination: {brain: "pusty", heart: "jest XD"}}
    },
    {
        id: '1',
        caseNumber: 'CAS-202301-001',
        deceasedName: 'John Doe',
        age: 54,
        gender: 'Male',
        dateOfDeath: new Date('2023-01-15'),
        dateOfAutopsy: new Date('2023-01-17'),
        placeOfDeath: 'Springfield General Hospital',
        causeOfDeath: 'Myocardial infarction',
        mannerOfDeath: 'Natural',
        autopsyPerformedBy: 'Dr. Emily Stanton',
        findings: {
            externalExamination: 'No visible external injuries. Normal decomposition.',
            internalExamination: {
                brain: 'Normal, no signs of hemorrhage or tumors',
                heart: 'Enlarged heart with signs of coronary artery disease',
                lungs: 'Normal, no signs of pneumonia or tumors',
                liver: 'Normal, no signs of cirrhosis or fatty liver disease',
                kidneys: 'Normal, no signs of acute or chronic injury',
                otherNotes: 'Gastrointestinal tract shows signs of recent meal, no obstructions.',
            },
            toxicologyResults: 'Negative for common toxins and alcohol. Trace amounts of prescription medication detected, within therapeutic levels.',
            microscopicExaminations: 'Heart tissue shows signs of fibrosis. No malignant cells detected in any examined tissues.',
            conclusion: 'The cause of death is myocardial infarction due to underlying coronary artery disease. Manner of death is natural.',
        },
    },
    {
        id: '2',
        caseNumber: 'CAS-202302-045',
        deceasedName: 'Alice Johnson',
        age: 29,
        gender: 'Female',
        dateOfDeath: new Date('2023-02-24'),
        dateOfAutopsy: new Date('2023-02-26'),
        placeOfDeath: 'Home',
        causeOfDeath: 'Acute intoxication',
        mannerOfDeath: 'Accident',
        autopsyPerformedBy: 'Dr. Henry Wallace',
        findings: {
            externalExamination: 'Minor abrasions on the forearms and knees. No other visible injuries.',
            internalExamination: {
                brain: 'Normal, no signs of injury or disease',
                heart: 'Normal, no pathological changes',
                lungs: 'Edema present, consistent with acute intoxication',
                liver: 'Normal, no significant findings',
                kidneys: 'Normal, no significant findings',
                otherNotes: 'Stomach contents include undigested food and liquid, no foreign objects.',
            },
            toxicologyResults: 'High levels of ethanol and traces of benzodiazepines detected.',
            microscopicExaminations: 'Lung tissue shows signs of edema. No other significant findings.',
            conclusion: 'The cause of death is acute intoxication due to combined effects of ethanol and benzodiazepines. Manner of death is accidental.',
        },
    },
    {
        id: '3',
        caseNumber: 'CAS-202303-078',
        deceasedName: 'Edward Norton',
        age: 67,
        gender: 'Male',
        dateOfDeath: new Date('2023-03-08'),
        dateOfAutopsy: new Date('2023-03-10'),
        placeOfDeath: 'Retirement Home',
        causeOfDeath: 'Stroke',
        mannerOfDeath: 'Natural',
        autopsyPerformedBy: 'Dr. Laura Hughes',
        findings: {
            externalExamination: 'No external injuries observed. Natural decomposition signs present.',
            internalExamination: {
                brain: 'Evidence of hemorrhagic stroke on the right hemisphere.',
                heart: 'Mild coronary artery disease, not significant.',
                lungs: 'Normal, no signs of recent infections.',
                liver: 'Slight signs of steatosis, otherwise normal.',
                kidneys: 'Chronic signs of nephritis observed.',
                otherNotes: 'No other significant internal abnormalities detected.',
            },
            toxicologyResults: 'No alcohol or toxic substances detected. Prescription medications within therapeutic levels.',
            microscopicExaminations: 'Brain sections confirm hemorrhagic stroke. Kidney sections show chronic nephritis.',
            conclusion: 'The cause of death determined to be a hemorrhagic stroke. The manner of death is natural.',
        },
    },
    {
        id: '4',
        caseNumber: 'CAS-202304-102',
        deceasedName: 'Margaret Atwood',
        age: 43,
        gender: 'Female',
        dateOfDeath: new Date('2023-04-22'),
        dateOfAutopsy: new Date('2023-04-24'),
        placeOfDeath: 'At home',
        causeOfDeath: 'Asphyxiation',
        mannerOfDeath: 'Suicide',
        autopsyPerformedBy: 'Dr. Simon Clarke',
        findings: {
            externalExamination: 'Markings consistent with ligature around the neck. No other injuries.',
            internalExamination: {
                brain: 'Normal, no acute pathological changes.',
                heart: 'Normal.',
                lungs: 'Congestion and edema present, consistent with asphyxiation.',
                liver: 'Normal.',
                kidneys: 'Normal.',
                otherNotes: 'Evidence of petechial hemorrhages in the eyes.',
            },
            toxicologyResults: 'No drugs or alcohol detected in the system.',
            microscopicExaminations: 'Lung tissue shows acute congestion, compatible with cause of death.',
            conclusion: 'The cause of death is asphyxiation by hanging. Manner of death is ruled as suicide.',
        },
    },
    {
        id: '5',
        caseNumber: 'CAS-202305-156',
        deceasedName: 'Charles Babbage',
        age: 58,
        gender: 'Male',
        dateOfDeath: new Date('2023-05-17'),
        dateOfAutopsy: new Date('2023-05-19'),
        placeOfDeath: 'Office',
        causeOfDeath: 'Acute myocardial infarction',
        mannerOfDeath: 'Natural',
        autopsyPerformedBy: 'Dr. Anita Gomez',
        findings: {
            externalExamination: 'No visible external injuries. Decomposition within expected range.',
            internalExamination: {
                brain: 'No significant pathological findings.',
                heart: 'Evidence of severe coronary artery disease, with acute myocardial infarction in the left ventricle.',
                lungs: 'Normal, no acute pathological findings.',
                liver: 'Mild fatty liver disease observed.',
                kidneys: 'Evidence of early-stage chronic kidney disease.',
                otherNotes: 'Gastrointestinal tract shows signs of recent meal, no abnormalities detected.',
            },
            toxicologyResults: 'Therapeutic levels of prescription medications found, no illicit drugs or alcohol.',
            microscopicExaminations: 'Heart tissue shows areas of recent infarction and chronic ischemic changes.',
            conclusion: 'The cause of death is acute myocardial infarction due to severe coronary artery disease. Manner of death is natural.',
        },
    }
];
